[package]
name = "hour-calc"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
color-eyre = "0.6.2"
ical = "0.7.0"
tracing = "0.1.37"
chrono = "0.4.23"
tabled = "0.10.0"

[dependencies.clap]
version = "4.0.32"
features = ["derive"]